### ISSUE TITLE
Question: `ts-fsrs` adds this repo as a reference example

### ISSUE THREAD

**Issue by ishiko732** [zsh-eng/spaced#31]
Can this repo be added as a reference example to `ts-fsrs`?

**Comment by zsh-eng** [comment]
@ishiko732 Sure! Would love that. Just to be clear, I'm still in the early stages of development :D

**Comment by ishiko732** [comment]
Hello, I have added it. Please feel free to contact me if you find it inappropriate and would like it to be removed.
